### ISSUE TITLE
Remove "SUBMIT A TALK Thank you for the overwhelming response. CFPs are now closed"

### ISSUE THREAD

**Issue by jeevandongre** [awsugblr/community-day-2019#111]
Remove "SUBMIT A TALK
Thank you for the overwhelming response. CFPs are now closed" statement completely.

**Comment by hnprashanth** [comment]
I suggest keeping this so that people know CFP is closed

**Comment by SathyaBhat** [comment]
agree with @hnprashanth. no reason to have it removed.

**Comment by roommen** [comment]
Agree. Closing the issue as WONTFIX ;-)
