### ISSUE TITLE
Photo and details for the Deep Learning Workshop speakers

### ISSUE THREAD

**Issue by jeevandongre** [awsugblr/community-day-2019#115]
We can update the photo and the details of the deep learning speaker on our website. 
Please find the details of the speaker as well as the details of the assistant. 

Speaker: https://www.linkedin.com/in/shajee-pulukkool-87611724/?originalSubdomain=in
Assistant: https://www.linkedin.com/in/shinduri-ks-5142a7156/?originalSubdomain=in

Please take photos of their LinkedIn account only.

**Comment by SathyaBhat** [comment]
this is done
