### ISSUE TITLE
Call for Proposal section

### ISSUE THREAD

**Issue by jeevandongre** [awsugblr/community-day-2019#22]
Last time we had a call for proposal tab on the website. Is it fine to have that again till we freeze the speakers?

**Comment by hnprashanth** [comment]
We should! We can also add guidelines, if it's a lot we can link to an external document

**Comment by hnprashanth** [comment]
@SathyaBhat need your inputs on this

**Comment by SathyaBhat** [comment]
Will add link to CFP and guidelines
