### ISSUE TITLE
AWS UG BLR Social Media

### ISSUE THREAD

**Issue by jeevandongre** [awsugblr/community-day-2019#58]
Can you put follows on twitter, facebook and linkedin button as well as share on social media buttons on the website.

**Comment by SathyaBhat** [comment]
we used ShareThis last time https://www.sharethis.com/

**Comment by roommen** [comment]
@SathyaBhat do DM the same. Let me see if I can play around with this and come up with something

**Comment by SathyaBhat** [comment]
this is done
